version: '3.3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    networks:
      default:
        ipv4_address: 192.168.1.200
    volumes:
      - homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
    restart: unless-stopped
    privileged: true

volumes:
  homeassistant-config:

networks:
  default:
    external:
      name: macvlan